DROP TABLE IF EXISTS message CASCADE;
CREATE TABLE message (
 id SERIAL PRIMARY KEY NOT NULL,
 buyer_id INTEGER REFERENCES artist(id) ON DELETE CASCADE NOT NULL,
 seller_id INTEGER REFERENCES artist(id) ON DELETE CASCADE NOT NULL,
 product_id INTEGER REFERENCES product(id) ON DELETE CASCADE NOT NULL,
 message TEXT,
 time TIMESTAMP
);
